env:
  - GO111MODULE=on
builds:
  - main: cmd/gkup/main.go
    binary: gkup
    ldflags: -X github.com/Miguel-Dorta/gkup/internal.Version={{.Version}}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: 386
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: macOS
